#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#homepage:
#    path: /app
#    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
#    defaults:
#        path: /posts
#        permanent: true
homepage:
    path: /posts
    controller: App\Controller\PostsController::posts

#posts_show:
#    path:       /posts/{id}
#    controller: App\Controller\PostsController::show
#    methods:    [POST]